<<<<<<< HEAD
# MCU設定
MCU = RP2040
BOOTLOADER = rp2040

# スプリット設定
SPLIT_KEYBOARD = yes
SERIAL_DRIVER = vendor
SPLIT_TRANSPORT_SYNC = yes

# デバッグ機能
CONSOLE_ENABLE = yes
DEBUG_ENABLE = yes

# RGB機能
RGBLIGHT_ENABLE = yes

# 無効化する機能
EXTRAKEY_ENABLE = no
ENCODER_ENABLE = no
MOUSEKEY_ENABLE = no

# 最適化
EXTRAFLAGS += -flto

# ソースファイル
SRC += naginata_v15.c
SRC += twpair_on_jis.c
SRC += split_debug.c

# デバッグフラグ
OPT_DEFS += -DCONSOLE_ENABLE
OPT_DEFS += -DDEBUG_KEYBOARD
OPT_DEFS += -DDEBUG_MATRIX_SCAN_RATE
OPT_DEFS += -DDEBUG_SPLIT
OPT_DEFS += -DDEBUG_TRANSPORT

# スプリットデバッグ設定の強化
OPT_DEFS += -DSPLIT_WATCHDOG_ENABLE
OPT_DEFS += -DSPLIT_WATCHDOG_TIMEOUT=3000
OPT_DEFS += -DSPLIT_USB_TIMEOUT=1000
OPT_DEFS += -DSPLIT_USB_TIMEOUT_POLL=10
OPT_DEFS += -DSPLIT_TRANSACTION_IDS_KB=20

=======
ENCODER_MAP_ENABLE = yes
>>>>>>> parent of 22e80d87bd (リポジトリ整理)
